/**
 * lib/strings/en.js
 * English UI strings. Keys mirror nl.js one to one.
 */

export const S = {
  header: {
    meldingen: "Notifications",
    instellingen: "Settings",
    alleTools: "All checks",
  },
  install: {
    knop: "Add to home screen",
    titel: "Put it on your home screen",
    uitleg:
      "One tap every morning and you know if it's on. And we'll give you a nudge when the weather turns near you.",
    iosStap:
      "Tap the share button and choose \u201cAdd to Home Screen\u201d. The check then opens as an app and you can turn on notifications.",
    later: "Not now",
  },
  meldingen: {
    dagen: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    briefing: "Briefing",
    vertrek: "Departure reminder",
    minVooraf: "min ahead",
    tijdToevoegen: "+ time",
    drempelAltijd: "always notify",
    drempelSlecht: "warn me on bad news",
    drempelGoed: "good news only",
  },
  algemeen: {
    liveOpgehaald: "fetched live at",
    bezig: "Working...",
    sluiten: "Close",
    ja: "Yes",
    nee: "No",
    vandaag: "today",
    weekdagen: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
  locatieTool: {
    jouwPlek: "Your place",
    kiesEerst: "Pick a place first: search an address, tap a favourite or use your location.",
    zoekStandaard: "Search an address or town...",
    favorietTitel: "Save as favourite",
    favorietActief: "Already in your favourites",
    favorietPrompt: "Name for this place:",
    geenData: "No usable weather data received. Try again in a moment.",
    databron: "Weather data: Open-Meteo hourly forecast,",
    leeg: "Pick your place and tap the check: you'll see the answer for today and the days ahead.",
    lieverNiet: "rather not",
    wisselvallig: "mixed",
    waarom: "Why:",
    besteBlok: "best window",
  },
  hub: {
    waarBenJe: "Where are you?",
    vandaagIn: "Today in",
    zoekStad: "Search your city...",
    mijnLocatie: "Use my location",
    locatieFout: "Couldn't get your location. Search your city above, works just as well.",
    kiesStad: "Pick your city above.",
    laden: "Checking the sky...",
    geenAntwoord: "No answer right now. Try the check itself.",
    binnenkort: "Coming soon",
    landnaam: "the Netherlands",
    checksVanVandaag: "Today's checks",
  },
  stem: {
    vraag: "Was the advice right today?",
    bedankt: "Thanks, noted.",
    jaLabel: "Yes, it was right",
    neeLabel: "No, it wasn't",
  },
  categorie: {
    kop: "Categories",
    intro: "Browse by topic and find the checks that fit your day.",
    bekijk: "View category",
    meerVragen: "More questions in this category",
    directAntwoord: "Direct answer",
    faqKop: "Frequently asked questions",
  },
  beslissingen: {
    zoekPlaceholder: "Search: coat, rain, bbq...",
    zoekLabel: "Search a weather decision",
    geenTreffers: "Nothing found. Try another word, or browse the list above.",
  },
  menu: {
    knop: "Menu",
    alle: "All checks",
    meer: "More",
    taalwissel: "Nederlands",
    groepen: { "Elke dag": "Every day", "Rondom huis": "Around the house", "Onderweg": "On the move" },
  },
  factoren: {
    kop: "What drives the verdict",
    temp: "Temperature",
    wind: "Wind",
    vocht: "Humidity",
    zon: "Sun",
    droog: "Dry",
    uv: "UV",
    uitleg: "How favourable each factor is right now for this activity. The bar shows favourability, the percentage its weight in the verdict.",
  },
  regenTiming: {
    kiesPlek: "Pick your place for the rain timing",
    nuNat: "It's raining now",
    eersteRegen: (tijd) => `Next shower around ${tijd}`,
    langDroog: "Dry for now",
    piek: (tijd, mm) => `Heaviest shower around ${tijd} (${mm} mm)`,
    eersteDroog: (tijd) => `Dry again from ${tijd}`,
    binnenUurJa: "Yes, rain within an hour",
    binnenUurNee: "No, dry for the next hour",
    dagdeel: { ochtend: "Morning", middag: "Afternoon", avond: "Evening" },
    dagdeelDroog: "dry",
    dagdeelBui: "showers",
    geenData: "No minute data for this place. Try the regular rain check.",
  },
  paraplu: {
    kiesPlek: "Pick your place for the umbrella advice",
    buitentijdVraag: "How long are you outside?",
    buitentijden: ["Briefly", "An hour", "All day"],
    ja: "Take an umbrella",
    nee: "Leave the umbrella at home",
    misschien: "Borderline: take it to be safe",
    redenNat: (tijd) => `rain falls around ${tijd} during your time outside`,
    redenDroog: "it stays dry during your time outside",
    redenVerspreid: "scattered showers today",
  },
  gerelateerd: {
    kop: "Also handy today",
  },
  bijgewerkt: (datum) => `Last updated: ${datum}. Weather data is fetched live with every check.`,
  nav: {
    openGoogle: "Open in Google Maps",
    openApple: "Open in Apple Maps",
    appleGeenStops: "Apple Maps can't handle stopovers; that route runs start to finish.",
  },
  voet: {
    checks: "Checks",
    uitleg: "Explainers",
    over: "About",
    overSite: "About",
    bronnen: "Sources and data",
    changelog: "Changelog",
    privacy: "Privacy",
    voorwaarden: "Terms",
    regel:
      "Not a weather report, an answer. Forecasts stay forecasts: have a look outside before you head out.",
  },
  kruimel: {
    home: "Home",
  },
};
