/**
 * lib/strings/en.js
 * English UI strings. Keys mirror nl.js one to one.
 */

export const S = {
  header: {
    meldingen: "Notifications",
    gekoppeld: "device linked",
    instellingen: "Settings",
    alleTools: "All checks",
  },
  install: {
    knop: "Add to home screen",
    titel: "Put it on your home screen",
    uitleg:
      "One tap every morning and you know if it's on. And we'll give you a nudge when the weather turns near you.",
    iosStap:
      "Tap the share button and choose \u201cAdd to Home Screen\u201d. The check then opens as an app and you can turn on notifications.",
    later: "Not now",
  },
  meldingen: {
    dagen: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    briefing: "Briefing",
    vertrek: "Departure reminder",
    minVooraf: "min ahead",
    tijdToevoegen: "+ time",
    drempelAltijd: "always notify",
    drempelSlecht: "warn me on bad news",
    drempelGoed: "good news only",
    meldingOm: "notify at",
    volgRoute: "follow the route plan",
    eigenVertrek: "ride departs at",
    doelDag: "advice for the whole day",
    doelVenster: "advice for a time window",
    vensterTot: "to",
    kopieerMa: "Apply Monday to all days",
    geenDagen: "Turn on at least one day to receive notifications.",
  },
  algemeen: {
    liveOpgehaald: "fetched live at",
    bezig: "Working...",
    sluiten: "Close",
    ja: "Yes",
    nee: "No",
    vandaag: "today",
    weekdagen: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
  locatieTool: {
    jouwPlek: "Your place",
    kiesEerst: "Pick a place first: search an address, tap a favourite or use your location.",
    zoekStandaard: "Search an address or town...",
    favorietTitel: "Save as favourite",
    favorietActief: "Already in your favourites",
    favorietPrompt: "Name for this place:",
    geenData: "No usable weather data received. Try again in a moment.",
    databron: "Weather data: Open-Meteo hourly forecast,",
    leeg: "Pick your place and tap the check: you'll see the answer for today and the days ahead.",
    lieverNiet: "rather not",
    wisselvallig: "mixed",
    waarom: "Why:",
    besteBlok: "best window",
  },
  hub: {
    waarBenJe: "Where are you?",
    vandaagIn: "Today in",
    zoekStad: "Search your city...",
    mijnLocatie: "Use my location",
    locatieFout: "Couldn't get your location. Search your city above, works just as well.",
    recentKop: "Recently used",
    themaKop: "Pick a theme",
    alleChecksTitel: "All checks in one place",
    alleChecksSub: "Including what is on the way, with the status for your location.",
    kiesStad: "Pick your city above.",
    laden: "Checking the sky...",
    geenAntwoord: "No answer right now. Try the check itself.",
    binnenkort: "Coming soon",
    landnaam: "the Netherlands",
    checksVanVandaag: "Today's checks",
  },
  stem: {
    vraag: "Was the advice right today?",
    bedankt: "Thanks for your feedback",
    jaLabel: "Yes, it was right",
    neeLabel: "No, it wasn't",
  },
  categorie: {
    kop: "Categories",
    intro: "Browse by topic and find the checks that fit your day.",
    bekijk: "View category",
    directAntwoord: "Direct answer",
    alleChecks: "All checks in this category",
    gerelateerdKop: "Related topics",
    faqKop: "Frequently asked questions",
  },
  beslissingen: {
    zoekPlaceholder: "Search: coat, rain, bbq...",
    zoekLabel: "Search a weather decision",
    geenTreffers: "Nothing found. Try another word, or browse the list above.",
    antwoordBadge: "Answer",
    inOntwikkeling: "In development",
  },
  menu: {
    knop: "Menu",
    alle: "All checks",
    meer: "More",
    populair: "Popular",
    taalwissel: "Nederlands",
  },
  factoren: {
    kop: "What drives the verdict",
    temp: "Temperature",
    wind: "Wind",
    vocht: "Humidity",
    zon: "Sun",
    droog: "Dry",
    uv: "UV",
    uitleg: "How favourable each factor is right now for this activity. The bar shows favourability, the percentage its weight in the verdict.",
  },
  regenTiming: {
    kiesPlek: "Pick your place for the rain timing",
    nuNat: "It's raining now",
    eersteRegen: (tijd) => `Next shower around ${tijd}`,
    langDroog: "Dry for now",
    piek: (tijd, mm) => `Heaviest shower around ${tijd} (${mm} mm)`,
    eersteDroog: (tijd) => `Dry again from ${tijd}`,
    binnenUurJa: "Yes, rain within an hour",
    binnenUurNee: "No, dry for the next hour",
    dagdeel: { ochtend: "Morning", middag: "Afternoon", avond: "Evening" },
    dagdeelDroog: "dry",
    dagdeelBui: "showers",
    geenData: "No minute data for this place. Try the regular rain check.",
  },
  paraplu: {
    kiesPlek: "Pick your place for the umbrella advice",
    buitentijdVraag: "How long are you outside?",
    buitentijden: ["Briefly", "An hour", "All day"],
    ja: "Take an umbrella",
    nee: "Leave the umbrella at home",
    misschien: "Borderline: take it to be safe",
    redenNat: (tijd) => `rain falls around ${tijd} during your time outside`,
    redenDroog: "it stays dry during your time outside",
    redenVerspreid: "scattered showers today",
  },
  instellingen: {
    persoonlijkKop: "Tune the checks to you",
    persoonlijkUitleg: "First pick a check, then set when it flips to yes or no. That way the advice matches your preferences.",
    kiesCheck: "Which check do you want to set up?",
    terugStandaard: "Back to defaults",
    plekkenKop: "My places",
    favorieten: "Favourite locations",
    favorietenLeeg: "No favourites yet. Pick a location in a check and tap the star to save it here.",
    routes: "Saved routes",
    routesLeeg: "No routes yet. Fill in your ride in the bike check and save it; tomorrow it's one tap away.",
    verwijder: "Delete",
    syncKop: "Take it to your other devices",
    syncUitleg: "With a link code your places and settings stay in sync across your phone and computer. Create a code and enter it on your other device.",
    syncActief: "Linked. Your settings are in sync on every device with this code:",
    syncKopieer: "Copy code",
    syncGekopieerd: "Copied",
    syncOntkoppel: "Unlink",
    syncMaak: "Create a link code",
    syncOfVul: "or enter an existing code",
    syncPlaceholder: "Link code from your other device",
    syncKoppel: "Link",
    syncBezig: "Working...",
  },
  gerelateerd: {
    kop: "Also handy today",
  },
  bijgewerkt: (datum) => `Last updated: ${datum}. Weather data is fetched live with every check.`,
  nav: {
    openGoogle: "Open in Google Maps",
    openApple: "Open in Apple Maps",
    appleGeenStops: "Apple Maps can't handle stopovers; that route runs start to finish.",
  },
  voet: {
    themas: "Themes",
    checks: "Checks",
    uitleg: "Explainers",
    over: "About",
    overSite: "About",
    bronnen: "Sources and data",
    changelog: "Changelog",
    privacy: "Privacy",
    voorwaarden: "Terms",
    regel:
      "Not a weather report, an answer. Forecasts stay forecasts: have a look outside before you head out.",
  },
  kruimel: {
    home: "Home",
  },
};
