/**
 * lib/strings/nl.js
 * Nederlandse UI-strings. Sleutels spiegelen en.js een op een; de selector
 * in index.js kiest per deployment.
 */

export const S = {
  header: {
    meldingen: "Meldingen",
    gekoppeld: "apparaat gekoppeld",
    instellingen: "Instellingen",
    alleTools: "Alle tools",
  },
  install: {
    knop: "Zet op beginscherm",
    titel: "Zet 'm op je beginscherm",
    uitleg:
      "Dan weet je elke ochtend met een tik of het kan. En we tikken je op de schouder als het weer omslaat bij jou in de buurt.",
    iosStap:
      "Tik op de deelknop en kies \u201cZet op beginscherm\u201d. Daarna opent de check als app en kun je meldingen aanzetten.",
    later: "Niet nu",
  },
  meldingen: {
    dagen: ["ma", "di", "wo", "do", "vr", "za", "zo"],
    briefing: "Briefing",
    vertrek: "Herinnering voor vertrek",
    minVooraf: "min vooraf",
    tijdToevoegen: "+ tijd",
    drempelAltijd: "altijd melden",
    drempelSlecht: "waarschuw bij slecht nieuws",
    drempelGoed: "alleen bij goed nieuws",
    meldingOm: "melding om",
    volgRoute: "volg de routeplanning",
    eigenVertrek: "rit vertrekt om",
    doelDag: "advies over de hele dag",
    doelVenster: "advies over een tijdvenster",
    vensterTot: "tot",
    kopieerMa: "Zet maandag op alle dagen",
    geenDagen: "Zet minstens een dag aan om meldingen te krijgen.",
  },
  algemeen: {
    liveOpgehaald: "live opgehaald om",
    bezig: "Bezig...",
    sluiten: "Sluiten",
    ja: "Ja",
    nee: "Nee",
    vandaag: "vandaag",
    weekdagen: ["zo", "ma", "di", "wo", "do", "vr", "za"],
  },
  locatieTool: {
    jouwPlek: "Jouw plek",
    kiesEerst: "Kies eerst een plek: zoek een adres, tik een favoriet aan of gebruik je locatie.",
    zoekStandaard: "Zoek een adres of plaats...",
    favorietTitel: "Bewaar als favoriet",
    favorietActief: "Staat bij je favorieten",
    favorietPrompt: "Naam voor deze plek:",
    geenData: "Geen bruikbare weerdata ontvangen. Probeer het zo nog eens.",
    databron: "Weerdata: Open-Meteo uurvoorspelling,",
    leeg: "Kies je plek en tik op de check: je ziet direct het antwoord voor vandaag en de dagen erna.",
    lieverNiet: "liever niet",
    wisselvallig: "wisselvallig",
    waarom: "Waarom:",
    besteBlok: "beste blok",
  },
  hub: {
    waarBenJe: "Waar ben je?",
    vandaagIn: "Vandaag in",
    zoekStad: "Zoek je stad...",
    mijnLocatie: "Gebruik mijn locatie",
    locatieFout: "Locatie ophalen lukte niet. Zoek je stad hierboven, dat werkt net zo goed.",
    populairKop: "Populaire checks",
    recentKop: "Recent gebruikt",
    themaKop: "Kies een thema",
    alleChecksTitel: "Alle checks op een plek",
    alleChecksSub: "Ook wat eraan komt, met de status voor jouw plek.",
    kiesStad: "Kies je stad hierboven.",
    laden: "Even naar de lucht kijken...",
    geenAntwoord: "Nu even geen antwoord. Probeer de check zelf.",
    binnenkort: "Binnenkort",
    landnaam: "Nederland",
    checksVanVandaag: "De checks van vandaag",
  },
  stem: {
    vraag: "Klopte het advies vandaag?",
    bedankt: "Bedankt voor je feedback",
    jaLabel: "Ja, klopte",
    neeLabel: "Nee, klopte niet",
    positief: (n) => (n === 1 ? "1 keer bevestigd vandaag" : `${n} keer bevestigd vandaag`),
    delen: "Deel deze check",
    gekopieerd: "Link gekopieerd",
  },
  categorie: {
    kop: "Categorieen",
    intro: "Blader per onderwerp en vind de checks die bij je dag horen.",
    bekijk: "Bekijk categorie",
    directAntwoord: "Direct antwoord",
    alleChecks: "Alle checks in deze categorie",
    gerelateerdKop: "Gerelateerde onderwerpen",
    faqKop: "Veelgestelde vragen",
  },
  beslissingen: {
    zoekPlaceholder: "Zoek: jas, regen, bbq...",
    zoekLabel: "Zoek een weerbeslissing",
    geenTreffers: "Niets gevonden. Probeer een ander woord, of kijk in de lijst hierboven.",
    inOntwikkeling: "In ontwikkeling",
  },
  menu: {
    knop: "Menu",
    alle: "Alle checks",
    meer: "Meer",
    populair: "Populair",
    taalwissel: "English",
  },
  factoren: {
    kop: "Wat het oordeel bepaalt",
    temp: "Temperatuur",
    wind: "Wind",
    vocht: "Luchtvochtigheid",
    zon: "Zon",
    droog: "Droog",
    uv: "Zonkracht",
    uitleg: "Hoe gunstig elke factor nu is voor deze bezigheid. De balk toont de gunstigheid, het percentage het gewicht in het oordeel.",
  },
  regenTiming: {
    kiesPlek: "Kies je plek voor de regentiming",
    nuNat: "Het regent nu",
    eersteRegen: (tijd) => `Eerstvolgende bui rond ${tijd}`,
    langDroog: "Voorlopig blijft het droog",
    piek: (tijd, mm) => `Zwaarste bui rond ${tijd} (${mm} mm)`,
    eersteDroog: (tijd) => `Weer droog vanaf ${tijd}`,
    binnenUurJa: "Ja, binnen een uur regen",
    binnenUurNee: "Nee, het komende uur droog",
    dagdeel: { ochtend: "Ochtend", middag: "Middag", avond: "Avond" },
    dagdeelDroog: "droog",
    dagdeelBui: "buien",
    geenData: "Geen minuutdata voor deze plek. Probeer de gewone regencheck.",
  },
  paraplu: {
    kiesPlek: "Kies je plek voor het paraplu-advies",
    buitentijdVraag: "Hoe lang ben je buiten?",
    buitentijden: ["Even, kort", "Een uurtje", "De hele dag"],
    ja: "Neem een paraplu mee",
    nee: "Laat de paraplu maar thuis",
    misschien: "Twijfelgeval: voor de zekerheid mee",
    redenNat: (tijd) => `rond ${tijd} valt er regen in jouw buitentijd`,
    redenDroog: "in jouw buitentijd blijft het droog",
    redenVerspreid: "er vallen verspreide buien vandaag",
  },
  instellingen: {
    persoonlijkKop: "Stel de checks op jou af",
    persoonlijkUitleg: "Kies eerst een check en pas daarna aan wanneer die op ja of nee springt. Zo krijg je advies dat bij jouw voorkeuren past.",
    kiesCheck: "Welke check wil je instellen?",
    terugStandaard: "Terug naar standaard",
    plekkenKop: "Mijn plekken",
    favorieten: "Favoriete locaties",
    favorietenLeeg: "Nog geen favorieten. Kies in een check een locatie en tik op de ster om hem hier te bewaren.",
    routes: "Opgeslagen routes",
    routesLeeg: "Nog geen routes. Vul je rit in bij de fietscheck en sla hem op; dan staat hij morgen met een tik klaar.",
    verwijder: "Verwijder",
    syncKop: "Meenemen naar je andere apparaten",
    syncUitleg: "Met een koppelcode staan je plekken en instellingen op je telefoon en je computer gelijk. Maak een code aan en vul die op je andere apparaat in.",
    syncActief: "Gekoppeld. Je instellingen staan gelijk op elk apparaat met deze code:",
    syncKopieer: "Kopieer code",
    syncGekopieerd: "Gekopieerd",
    syncOntkoppel: "Ontkoppelen",
    syncMaak: "Maak een koppelcode",
    syncOfVul: "of vul een bestaande code in",
    syncPlaceholder: "Koppelcode van je andere apparaat",
    syncKoppel: "Koppel",
    syncBezig: "Bezig...",
  },
  gerelateerd: {
    kop: "Ook handig vandaag",
  },
  bijgewerkt: (datum) => `Laatst bijgewerkt: ${datum}. Weerdata wordt bij elke check live opgehaald.`,
  nav: {
    openGoogle: "Open in Google Maps",
    openApple: "Open in Apple Maps",
    appleGeenStops: "Apple Maps kan geen tussenstops aan; daar gaat de route van start naar eind.",
  },
  voet: {
    themas: "Thema's",
    checks: "Checks",
    uitleg: "Uitleg",
    over: "Over",
    overSite: "Over",
    bronnen: "Bronnen en data",
    changelog: "Changelog",
    privacy: "Privacy",
    voorwaarden: "Voorwaarden",
    regel:
      "Geen weerbericht, maar een antwoord. Voorspellingen blijven voorspellingen: kijk voor je vertrekt ook even naar buiten.",
  },
  kruimel: {
    home: "Home",
  },
};
