/**
 * content/versies.en.js
 * Release history for the changelog page, English wording.
 */

export const VERSIES = [
  {
    versie: "3.23.0",
    codenaam: "Boreas",
    datum: "2026-07-17",
    zin: "The bike check got tidied up: building your route and the map sit side by side again, the map no longer slides over the menu, and tapping a leg card on your phone takes you straight to the map. On top of that, every town page now carries its own correct title and description, and the town buttons say where they lead.",
  },
  {
    versie: "3.22.0",
    codenaam: "Foehn",
    datum: "2026-07-17",
    zin: "The homepage now puts the most popular guides first based on real thumbs-up, and the explainers on the theme pages fold away so you reach the point faster. Titles catch more ways of searching (will it, is it, can I). And a few checks now carry a short advice block with a handy tip.",
  },
  {
    versie: "3.21.0",
    codenaam: "Chinook",
    datum: "2026-07-17",
    zin: "Wherever a check mentions another check, that mention is now a real link: from the walking question about running to the icy roads check pointing at the scraping check. On the theme pages too, in the explainers and season blocks. So you click straight through to the answer the text is talking about.",
  },
  {
    versie: "3.20.0",
    codenaam: "Bayamo",
    datum: "2026-07-16",
    zin: "Fixed a lurking bug where some checks already said \"passed\" in the afternoon while a good window was still ahead. The bike check now shows right at the top whether it's a good cycling day, with the toughest leg and the reasons behind it, plus factor bars like the other checks. And several places in the text now link straight to the check they're talking about.",
  },
  {
    versie: "3.19.0",
    codenaam: "Harmattan",
    datum: "2026-07-16",
    zin: "Every check now points to its related checks and its theme (including the breadcrumb), and the theme pages reference each other more sensibly. On top of that, the checks and themes answer over forty new questions, from what to wear at 10 degrees to UV index 3 and the pollen calendar.",
  },
  {
    versie: "3.18.0",
    codenaam: "Zonda",
    datum: "2026-07-16",
    zin: "Maintenance under the hood: five checks (patio, barbecue, running, beach, car wash) now run on the same engine as the ten new checks, with exactly the same behaviour as before. Visible difference: every check now shows the legend bar under the hour strip; it was missing on some checks.",
  },
  {
    versie: "3.17.0",
    codenaam: "Passaat",
    datum: "2026-07-16",
    zin: "Ten new checks in one go: walking, outdoor workouts, padel or tennis, SUP or kayak, picnic weather, outdoor swimming, stargazing (with moon phase), mowing, window cleaning and your solar panel yield day. That also delivers the three checks that were marked in development. In the notifications panel your bike routes now sit under the bike check, and you can add a route right there.",
  },
  {
    versie: "3.16.0",
    codenaam: "Maestro",
    datum: "2026-07-16",
    zin: "Three new checks: wash the car today, scrape tomorrow and are the roads icy (winter has its first checks). Notifications are now set and collapsed per check, every route has its own on-off switch, and a silent bug that made notifications stop after a while is fixed: the link now repairs itself.",
  },
  {
    versie: "3.15.0",
    codenaam: "Marin",
    datum: "2026-07-16",
    zin: "Two new checks: running weather today (with your best running window, because cool beats warm) and beach weather today (with a strict wind limit, because there is no shelter on the beach). Every theme now truly has its own colour, and All checks shows just the coloured dot per check.",
  },
  {
    versie: "3.14.0",
    codenaam: "Ostro",
    datum: "2026-07-16",
    zin: "The footer is back under every theme page and the coloured dots on All checks now actually work: green, orange or red per check, defaulting to the whole country until you pick a place. The homepage got tidy theme blocks, a row with your three most recent checks and a clear button to everything. Every check now has its own icon.",
  },
  {
    versie: "3.13.0",
    codenaam: "Solano",
    datum: "2026-07-16",
    zin: "The homepage now shows the way: the seven themes sit at the top as tappable buttons, a clear button to all checks sits below the cards, and the themes joined the footer. And the calm background tint and large icon on the theme pages are finally visible; a bug had hidden them behind the page.",
  },
  {
    versie: "3.12.0",
    codenaam: "Gregale",
    datum: "2026-07-16",
    zin: "The theme pages are nicer to scroll through: the picker now uses the same card style as the checks, the guidance blocks got check marks, accent borders and season icons, and the arrow finally points right.",
  },
  {
    versie: "3.11.0",
    codenaam: "Libeccio",
    datum: "2026-07-16",
    zin: "All seven theme pages are now equally complete: who the page helps, a picker, guidance per situation and season, every check as a card and a FAQ block. Fifteen questions that used to say 'coming soon' now link straight to their answer, and the pages got a calm background in the theme colour.",
  },
  {
    versie: "3.10.0",
    codenaam: "Levante",
    datum: "2026-07-15",
    zin: "Everything now has one name everywhere: each check has a single title and each category a fixed name and colour, the same on the homepage, in the menu and on the theme pages. On All checks you see each check's outcome for your location as a coloured dot with a label, and questions in development sit quietly below. Seven home-and-garden questions now link straight to their answer.",
  },
  {
    versie: "3.9.0",
    codenaam: "Sirocco",
    datum: "2026-07-15",
    zin: "Category pages now help you choose first: a short picker at the top takes you to the right check or answer, followed by the explanation and all checks. The first full page is Home, garden and car, with answers to questions like washing the car, mowing the lawn and painting outside. The bike check now also sits neatly under Sport and exercise.",
  },
  {
    versie: "3.8.0",
    codenaam: "Mistral",
    datum: "2026-07-14",
    zin: "Notifications can now be set per weekday: each day gets its own notification time, plus what the advice covers (your departure time that day, the whole day, or a time window such as 8 to 12). The notification itself is clearer, starts with the answer and opens the right check when you tap it. Saved times always jump to today when you open the check.",
  },
  {
    versie: "3.7.7",
    codenaam: "Etesian patch 7",
    datum: "2026-07-14",
    zin: "The rain and umbrella checks now look like the other checks: the same location picker with favourites, a button to check again, and the source with the fetch time. On a wide screen the answer sits next to your location.",
  },
  {
    versie: "3.7.6",
    codenaam: "Etesian patch 6",
    datum: "2026-07-14",
    zin: "More personal titles: the question above a check is now more often about \"I\" than \"it\". The hay fever, barbecue and umbrella questions read more naturally.",
  },
  {
    versie: "3.7.5",
    codenaam: "Etesian patch 5",
    datum: "2026-07-14",
    zin: "Roomier layout for the answer: on tablet and desktop the answer now sits next to your location instead of below it, with the explanation underneath. On the phone everything stays neatly stacked. The weather factors, day picker and hours strip sit below.",
  },
  {
    versie: "3.7.4",
    codenaam: "Etesian patch 4",
    datum: "2026-07-14",
    zin: "The thumb under a check now shows how many people have ever marked the check as correct, not just today. The thumbs are clearer (up green, down red), the question \"Was today's advice right?\" stands out more, and the share button now catches the eye.",
  },
  {
    versie: "3.7.3",
    codenaam: "Etesian patch 3",
    datum: "2026-07-14",
    zin: "Technical fix: the thumbs under a check were not loading their counts in production because of a small mistake in the address the site uses to call the database (a double slash). That address is now cleaned up automatically, so the counter and the push notifications that use the same connection work again.",
  },
  {
    versie: "3.7.2",
    codenaam: "Etesian patch 2",
    datum: "2026-07-14",
    zin: "The bike check has been tidied up: each ride now shows a single verdict word (no more double label), the contradictory kilometres are gone because the wind summary is now the only place that tells you where and how much headwind there is, and the day banner uses that summary of the toughest ride. Behind the scenes the push notifications run on an external clock, so they go out on time even on the free hosting plan.",
  },
  {
    versie: "3.7.1",
    codenaam: "Etesian patch",
    datum: "2026-07-14",
    zin: "A technical fix for how pages appear in Google: the breadcrumbs (the path line at the top of a page) now always provide clean, complete addresses, after a Search Console warning.",
  },
  {
    versie: "3.7.0",
    codenaam: "Etesian",
    datum: "2026-07-13",
    zin: "Feedback and sharing have been redesigned in the house style: two thumbs, only the count of confirmations next to the thumb up, a negative vote gets just a thank you. The settings menu is split into clear sections with the link code to keep your phone and computer in sync. The header now stays fixed at the top, the footer and the blocks in All checks have clear borders, and tool titles plus FAQ questions have been sharpened brand-wide.",
  },
  {
    versie: "3.6.0",
    codenaam: "Bora",
    datum: "2026-07-13",
    zin: "The storefronts are live: every category is now its own rankable page on the root (rain-or-dry, clothing, outdoors-leisure, sport-exercise, home-garden-car, sun-air-hayfever, winter-safety) with decision logic, situations, seasonal context and FAQ. The first storefront, rain or dry, is fully built, with two new checks: when will it rain (on 15-minute rain data) and umbrella today.",
  },
  {
    versie: "3.5.0",
    codenaam: "Tramontane",
    datum: "2026-07-13",
    zin: "Foundation for the storefronts: every check now belongs to a category (outdoors, clothing, home and garden, on the move, health) with its own overview page, ready to become a storefront later. Under every answer sit weather-factor bars showing what drives the verdict (temperature, wind, humidity, sun), and push notifications are now actually sent on time.",
  },
  {
    versie: "3.4.0",
    codenaam: "Ponente",
    datum: "2026-07-13",
    zin: "An explanation under every verdict (a why line with the decisive reason), and with a known place every check shows its answer straight away without an extra tap. New hay fever check on its own pollen source (CAMS) with the calmest window of the day, plus three clothing question pages (shorts, coat, T-shirt weather). New overview page with all weather decisions and search, feedback buttons that no longer flash away, and on mobile square tiles plus a sticky answer bar.",
  },
  {
    versie: "3.3.0",
    codenaam: "Meltemi",
    datum: "2026-07-13",
    zin: "Tighter and more consistent: every hub card now follows a fixed layout (question, verdict badge on the right, two-line explainer, its own CTA) with the watermark as backdrop. New UV check with skin type and burn time. The text links moved into a slide-out menu, the FAQ collapses, and every advice now carries a vote counter, a share button, related checks and a last-updated line.",
  },
  {
    versie: "3.2.0",
    codenaam: "Sirocco",
    datum: "2026-07-13",
    zin: "The English release: the whole site now ships in two languages from one codebase, as Good day for it? on its own domain. New check: the barbecue, evening-focused and with smoke advice that tells you where not to put the table. Compass points, decimals and every generated sentence now follow the site language.",
  },
  {
    versie: "3.1.0",
    codenaam: "Chinook",
    datum: "2026-07-13",
    zin: "Every check now answers in its own words: Hang it out, Good to go, Perfect patio weather. The homepage opens with live answers for the whole country (or your town), the settings speak plain language with choice buttons, and the cards got colour and character.",
  },
  {
    versie: "3.0.0",
    codenaam: "Levante",
    datum: "2026-07-13",
    zin: "Answers in words: every check now leads with Yes or No plus a verdict word from Very poor to Ideal. The homepage got more compact and shows the live answer per card, you can rate the advice per day with a thumb, the outfit check got a little figure and the copy across the site got more direct.",
  },
  {
    versie: "2.2.0",
    codenaam: "Zephyr",
    datum: "2026-07-12",
    zin: "Two new checks (outfit and patio) on a shared weather base, the laundry verdict untangled from the clock (a conditions score plus a separate can-I-still-make-it status with drying time), open-in-Maps buttons on the bike route, a richer hub with plain-language explainers, and the whole site mobile-first with notifications and settings as icons top right.",
  },
  {
    versie: "2.1.0",
    codenaam: "Mistral",
    datum: "2026-07-12",
    zin: "The bike check learned chains: multiple stops on one day, per-leg departure times and a day verdict set by the toughest ride.",
  },
  {
    versie: "2.0.0",
    codenaam: "Passaat",
    datum: "2026-07-11",
    zin: "From one tool to a hub: shared register, one design system and the laundry check as the second resident.",
  },
  {
    versie: "1.0.0",
    codenaam: "Kopwind",
    datum: "2026-07-11",
    zin: "The first release: one question, one answer. Can I bike to work today, with the wind per part of the route.",
  },
];
