/**
 * content/versies.js
 * Releasegeschiedenis voor de changelog-pagina, gesynct met CHANGELOG.md.
 * Nieuwste bovenaan.
 */

export const VERSIES = [
  {
    versie: "3.33.0",
    codenaam: "Autan",
    datum: "2026-07-20",
    zin: "Vijf nieuwe checks: kan het springkussen buiten (windveiligheid voor luchtkussens), kan ik naar de speeltuin (droog en aangenaam voor kinderen), kan ik bestrating leggen (droog venster en geen nachtvorst), kan ik mijn dekbed buiten luchten (droogste en zonnigste blok) en moet ik de buitenkraan aftappen (vorstwaarschuwing voor de komende nachten). Verder is de bol-partneraanmelding afgewezen, dus de tracking staat nu uit en de links zijn gewone winkellinks tot je een ander netwerk kiest. En de site is grondig nagelopen op onherleidbaarheid: de naam is overal uit de code gehaald en er staat een volledige veiligheids- en anonimiteitschecklist bij.",
  },
  {
    versie: "3.32.0",
    codenaam: "Levante",
    datum: "2026-07-19",
    zin: "Vier nieuwe checks: kan ik vandaag beton storten (met de vorst van de nacht erna erbij), kan ik veilig het dak op (een veiligheidscheck op wind en gladheid), kan ik het zwembad opzetten (warm en zonnig genoeg) en is het muggenweer vanavond (waarbij groen juist weinig muggen betekent). Verder de bol-partnerlinks definitief live gezet met de echte SiteId, en de security headers geverifieerd tegen een draaiende server.",
  },
  {
    versie: "3.31.0",
    codenaam: "Sirocco",
    datum: "2026-07-19",
    zin: "Een grote opschoonronde na een audit van de hele site. De regenkaart op de homepage geeft nu een timing-antwoord in plaats van een of-antwoord, zes pagina's die geen kop bovenaan hadden hebben er weer een, een dubbele slippers-vermelding is weg en de vragen in het overzicht kloppen weer met de titels op de pagina (geen misleidend buiten rijden of vaag reinigen meer). Verder de affiliate-adviesblokken live gezet met bol als basis, en de statistiek achter een cookiebalk gezet zodat er pas na toestemming een analytische cookie komt, met bijpassende security headers.",
  },
  {
    versie: "3.30.0",
    codenaam: "Mistral",
    datum: "2026-07-18",
    zin: "Zes nieuwe keuzehulpen rond winter en klussen in en om het huis, plus uitgezocht hoe affiliate zou werken. Nieuw: buiten schilderen, hout behandelen (beitsen en olien), het terras reinigen, planten beschermen tegen nachtvorst, sneeuwpret en strooien. Bijzonder: de sneeuwpretcheck gebruikt als enige het sneeuwdek, de vorstcheck rekent stralingsvorst mee (op een heldere nacht is het aan de grond kouder dan de lucht), en de strooicheck gaat over je eigen stoep, niet over de weg. Verder een stille fout hersteld waardoor de mist- en vischeck live geen zicht- en drukdata kregen.",
  },
  {
    versie: "3.29.0",
    codenaam: "Ghibli",
    datum: "2026-07-18",
    zin: "Vijftien nieuwe keuzehulpen erbij, en drie vervelende bugs eruit. Nieuw: golfen, skeeleren, motorrijden, de hond uitlaten, vliegeren, de vuurkorf, drone vliegen, paardrijden, vissen, natuurijs, mist, storm, de houtkachel, het huis koel houden en kamperen. Bijzonder: de vischeck gebruikt als enige de luchtdruk, de vliegercheck zoekt juist de beste wind in plaats van de minste, en de natuurijscheck weegt de vorst maar laat het oordeel over het ijs altijd aan de ijsclub. Verder losten we een paar fouten op die het zoekverkeer raakten, waaronder de breadcrumb-melding in Search Console.",
  },
  {
    versie: "3.28.0",
    codenaam: "Ostria",
    datum: "2026-07-18",
    zin: "De tuin heeft nu een eigen plek: een nieuwe categorie Tuin en planten met drie nieuwe checks. De onkruidcheck kiest de methode van de dag (schoffelen bij droog en zon, wieden bij vochtige grond), de gietcheck zegt eerlijk wanneer de regen het werk doet, en de zaaicheck kent de twee zaaivensters van het gazon. Plus nieuwe antwoorden over bemesten, bladeren en de moestuin.",
  },
  {
    versie: "3.27.0",
    codenaam: "Solano",
    datum: "2026-07-18",
    zin: "Elke stadpagina toont het antwoord nu direct bovenaan, ook voordat de check geladen is, en de fietscheck heeft eindelijk zijn eigen statusstip (op de spitsen). Nieuw: de snoeicheck weegt vorst, nat en hitte en vertelt wat het snoeiseizoen deze maand toelaat, met een vogelnest-herinnering voor wie hagen snoeit. Plus drie nieuwe tuinvragen in het overzicht.",
  },
  {
    versie: "3.26.0",
    codenaam: "Gregale",
    datum: "2026-07-18",
    zin: "De adviezen klinken nu natuurlijker en kloppen beter met het moment: geen krabadvies in juli meer (dat was een echte fout), geen tips over dagdelen of buien die al voorbij zijn, en als het de hele dag goed is zeggen we dat gewoon. Op de fietstool staat na het checken de heenweg klaar, en op de homepage kun je nu direct een keuzehulp zoeken.",
  },
  {
    versie: "3.25.0",
    codenaam: "Pampero",
    datum: "2026-07-17",
    zin: "Nieuw: de wielrencheck zoekt het beste blok voor een rit op de racefiets, met droog wegdek en hanteerbare wind voorop. De paraplu- en regentiming-check tonen nu ook een statusstip op de homepage, en de kledingcheck kreeg er een slippersvraag bij met direct ja of nee.",
  },
  {
    versie: "3.24.0",
    codenaam: "Khamsin",
    datum: "2026-07-17",
    zin: "De kledingvragen geven nu zelf antwoord: op Moet ik een jas aan zie je meteen ja of nee, met een eigen statusstip in het overzicht. Links naar veelgestelde vragen klappen het antwoord voortaan automatisch open, de footer is opgeruimd en op je telefoon kun je de site nu direct op je beginscherm zetten.",
  },
  {
    versie: "3.23.0",
    codenaam: "Boreas",
    datum: "2026-07-17",
    zin: "De fietscheck is opgeruimd: route invullen en de kaart staan weer netjes naast elkaar, de kaart schuift niet meer over het menu en een tik op een ritkaart brengt je op je telefoon direct naar de kaart. Daarnaast hebben alle stadspagina's nu hun eigen correcte titel en omschrijving, en vertellen de stadsknoppen meteen waar ze heen gaan.",
  },
  {
    versie: "3.22.0",
    codenaam: "Foehn",
    datum: "2026-07-17",
    zin: "De homepage zet de populairste keuzehulpen nu voorop op basis van echte duimpjes, en de uitleg op de themapagina's is inklapbaar zodat je sneller bij de kern komt. Titels vangen meer manieren van zoeken af (wordt het, gaat het, kan ik). En bij een paar checks staat nu een kort adviesblok met een handige tip.",
  },
  {
    versie: "3.21.0",
    codenaam: "Chinook",
    datum: "2026-07-17",
    zin: "Overal waar een check een andere check noemt, is die vermelding nu een echte link: van de wandelvraag over hardlopen tot de gladheidscheck die naar de krabcheck wijst. Ook op de themapagina's zelf, in de uitleg en de seizoensblokken. Zo klik je direct door naar het antwoord waar de tekst het over heeft.",
  },
  {
    versie: "3.20.0",
    codenaam: "Bayamo",
    datum: "2026-07-16",
    zin: "Een sluimerende bug gefixt waardoor een aantal checks 's middags al \"geweest\" zei terwijl er nog een prima moment voor de deur lag. De fietscheck toont nu meteen boven aan of het een goede fietsdag is, met de zwaarste rit en de redenen erbij, en factorbalken zoals de andere checks. En op meerdere plekken in de tekst staan nu directe links naar de check waar het net over gaat.",
  },
  {
    versie: "3.19.0",
    codenaam: "Harmattan",
    datum: "2026-07-16",
    zin: "Elke check verwijst nu naar zijn verwante checks en naar zijn thema (ook in het kruimelpad), en de themapagina's verwijzen slimmer naar elkaar. Daarnaast beantwoorden de checks en thema's ruim veertig nieuwe vragen, van wat trek ik aan bij 10 graden tot zonkracht 3 en de pollenkalender.",
  },
  {
    versie: "3.18.0",
    codenaam: "Zonda",
    datum: "2026-07-16",
    zin: "Onderhoudsronde onder de motorkap: vijf checks (terras, barbecue, hardlopen, strand, autowassen) draaien nu op dezelfde motor als de tien nieuwe checks, met exact hetzelfde gedrag als voorheen. Zichtbaar verschil: elke check toont nu de legenda-balk onder de urenstrip; die ontbrak bij een deel van de checks.",
  },
  {
    versie: "3.17.0",
    codenaam: "Passaat",
    datum: "2026-07-16",
    zin: "Tien nieuwe checks in een keer: wandelen, buiten sporten, padel of tennis, suppen of kajakken, picknickweer, buiten zwemmen, sterrenkijken (met maanfase), grasmaaien, ramen wassen en de opbrengstdag van je zonnepanelen. Daarmee zijn ook de drie checks die als in ontwikkeling stonden er echt. In het meldingenpaneel staan je fietsroutes nu netjes onder de fietscheck en kun je een route direct daar toevoegen.",
  },
  {
    versie: "3.16.0",
    codenaam: "Maestro",
    datum: "2026-07-16",
    zin: "Drie nieuwe checks: kan ik de auto wassen vandaag, moet ik morgen krabben en is het glad op de weg (winter heeft zijn eerste checks). Meldingen zijn nu per check in te stellen en in te klappen, elke route heeft een eigen aan-uitknop, en een stille bug waardoor meldingen na een tijdje stopten is verholpen: de koppeling herstelt zichzelf voortaan.",
  },
  {
    versie: "3.15.0",
    codenaam: "Marin",
    datum: "2026-07-16",
    zin: "Twee nieuwe checks: is het hardloopweer vandaag (met het beste loopblok, want koel loopt lekkerder dan warm) en is het strandweer vandaag (met een strenge windgrens, want op het strand is geen luwte). Elk thema heeft nu ook echt zijn eigen kleur, en op Alle checks zie je per check alleen nog het gekleurde bolletje.",
  },
  {
    versie: "3.14.0",
    codenaam: "Ostro",
    datum: "2026-07-16",
    zin: "De voet staat weer onder elke themapagina en de gekleurde bolletjes op Alle checks doen het nu echt: groen, oranje of rood per check, standaard voor heel Nederland tot je een plek kiest. De homepage kreeg nette themablokken, een rijtje met je drie laatst gebruikte checks en een duidelijke knop naar alles. Elke check heeft voortaan een eigen icoon.",
  },
  {
    versie: "3.13.0",
    codenaam: "Solano",
    datum: "2026-07-16",
    zin: "De homepage wijst nu de weg: bovenaan staan de zeven thema's als klikbare knoppen, onder de kaarten staat een duidelijke knop naar alle checks, en de thema's staan ook in de voet. En de rustige achtergrondkleur en het grote icoon op de themapagina's zijn nu echt zichtbaar; die zaten door een foutje achter de pagina verstopt.",
  },
  {
    versie: "3.12.0",
    codenaam: "Gregale",
    datum: "2026-07-16",
    zin: "De themapagina's zijn prettiger om door te scrollen: de keuzehulp staat in dezelfde kaartstijl als de checks, de uitlegblokken kregen vinkjes, accentranden en seizoensiconen, en het pijltje wijst voortaan gewoon naar rechts.",
  },
  {
    versie: "3.11.0",
    codenaam: "Libeccio",
    datum: "2026-07-16",
    zin: "Alle zeven themapagina's zijn nu even compleet: wie de pagina helpt, een keuzehulp, uitleg per situatie en seizoen, alle checks als kaarten en een veelgestelde-vragenblok. Vijftien vragen die eerst 'binnenkort' waren linken nu direct naar hun antwoord, en de pagina's kregen een rustige achtergrond in de kleur van het thema.",
  },
  {
    versie: "3.10.0",
    codenaam: "Levante",
    datum: "2026-07-15",
    zin: "Alles heet nu overal hetzelfde: elke check heeft een titel en elke categorie een naam en kleur, gelijk op de homepage, in het menu en op de themapagina's. Op Alle checks zie je per check direct de uitkomst voor jouw plek als gekleurd bolletje met label, en vragen in ontwikkeling staan er rustig onder. Zeven huis-tuinvragen linken nu direct naar hun antwoord.",
  },
  {
    versie: "3.9.0",
    codenaam: "Sirocco",
    datum: "2026-07-15",
    zin: "De categoriepagina's helpen je nu eerst kiezen: bovenaan een korte keuzehulp die je bij de juiste check of het juiste antwoord brengt, daarna de uitleg en alle checks. De eerste volledige pagina is Huis, tuin en auto, met antwoorden op vragen als auto wassen, grasmaaien en buiten schilderen. Ook is de fietscheck nu netjes bij Sport en beweging te vinden.",
  },
  {
    versie: "3.8.0",
    codenaam: "Mistral",
    datum: "2026-07-14",
    zin: "Meldingen zijn nu per weekdag in te stellen: op elke dag een eigen tijd voor de melding, en waar het advies over gaat (je vertrektijd die dag, de hele dag, of een tijdvenster zoals tussen 8 en 12). De melding zelf is duidelijker, begint met het antwoord en opent bij het aantikken meteen de juiste check. Bewaarde tijden springen bij het openen altijd naar vandaag.",
  },
  {
    versie: "3.7.7",
    codenaam: "Etesian patch 7",
    datum: "2026-07-14",
    zin: "De regen- en paraplucheck zien er nu net zo uit als de andere checks: dezelfde plekkiezer met favorieten, een knop om opnieuw te checken, en de bron met het ophaalmoment. Op een breed scherm staat het antwoord naast je plek.",
  },
  {
    versie: "3.7.6",
    codenaam: "Etesian patch 6",
    datum: "2026-07-14",
    zin: "Persoonlijker titels: de vraag boven een check gaat nu vaker over \"ik\" in plaats van \"het\". \"Krijg ik vandaag hooikoorts?\" is nu \"Heb ik vandaag last van hooikoorts?\", en ook de barbecue- en parapluvraag lezen logischer.",
  },
  {
    versie: "3.7.5",
    codenaam: "Etesian patch 5",
    datum: "2026-07-14",
    zin: "Ruimere indeling van de uitslag: op tablet en desktop staat het antwoord nu naast je plek in plaats van eronder, met de toelichting eronder. Op de telefoon blijft alles netjes onder elkaar. De weerfactoren, de dagkiezer en de urenstrip staan daaronder.",
  },
  {
    versie: "3.7.4",
    codenaam: "Etesian patch 4",
    datum: "2026-07-14",
    zin: "Het duimpje onder een check laat nu zien hoeveel mensen de check ooit als kloppend hebben gemarkeerd, niet meer alleen vandaag. De duimen zijn duidelijker (omhoog groen, omlaag rood), de vraag \"Klopte het advies vandaag?\" is beter zichtbaar en de deelknop springt er nu uit.",
  },
  {
    versie: "3.7.3",
    codenaam: "Etesian patch 3",
    datum: "2026-07-14",
    zin: "Technische fix: de duimpjes onder een check haalden in productie de aantallen niet op door een foutje in het adres waarmee de site de database aanroept (een dubbele schuine streep). Dat adres wordt nu automatisch schoongemaakt, zodat de teller en de pushmeldingen die dezelfde verbinding gebruiken weer werken.",
  },
  {
    versie: "3.7.2",
    codenaam: "Etesian patch 2",
    datum: "2026-07-14",
    zin: "De fietscheck is opgeschoond: per rit staat nog maar een oordeelwoord (geen dubbel label meer), de tegenstrijdige kilometers zijn weg doordat de windsamenvatting nu de enige plek is die vertelt waar en hoeveel tegenwind er is, en de dagbanner gebruikt die samenvatting van de zwaarste rit. \"Cijfer gedrukt door\" heet nu \"Wat telt tegen\". Achter de schermen draaien de pushmeldingen op een externe klok, zodat ze ook op het gratis hostingplan op tijd vertrekken.",
  },
  {
    versie: "3.7.1",
    codenaam: "Etesian patch",
    datum: "2026-07-14",
    zin: "Technische fix voor de weergave in Google: de broodkruimels (de padregel bovenaan een pagina) leveren nu altijd nette, volledige adressen aan, na een melding van Search Console.",
  },
  {
    versie: "3.7.0",
    codenaam: "Etesian",
    datum: "2026-07-13",
    zin: "Feedback en delen zijn opnieuw vormgegeven in de huisstijl: twee duimen, alleen het aantal bevestigingen naast de duim omhoog, een negatieve stem krijgt enkel een bedankje. Het instellingenmenu is opgedeeld in heldere secties met de koppelcode om je telefoon en computer gelijk te houden. De header blijft nu vast bovenaan, de footer en de blokken in Alle checks hebben duidelijke randen, en tool-titels plus FAQ-vragen zijn merkbreed aangescherpt op de vraag Kan het vandaag.",
  },
  {
    versie: "3.6.0",
    codenaam: "Bora",
    datum: "2026-07-13",
    zin: "De storefronts staan: elke categorie is nu een eigen rankbare pagina op de root (regen-en-droog, kleding, buiten-vrije-tijd, sport-beweging, huis-tuin-auto, zon-lucht-hooikoorts, winter-veiligheid) met beslislogica, situaties, seizoenscontext en FAQ. De eerste storefront Regen en droog is volledig uitgewerkt, met twee nieuwe checks: wanneer gaat het regenen (op 15-minuten neerslagdata) en paraplu mee.",
  },
  {
    versie: "3.5.0",
    codenaam: "Tramontane",
    datum: "2026-07-13",
    zin: "Fundament voor de storefronts: elke check hoort nu bij een categorie (buiten, kleding, huis en tuin, onderweg, gezondheid) met een eigen overzichtspagina, klaar om later etalage te worden. Onder elk antwoord staan weerfactoren-balken die tonen wat het oordeel bepaalt (temperatuur, wind, vocht, zon), en de pushmeldingen worden nu echt op tijd verstuurd.",
  },
  {
    versie: "3.4.0",
    codenaam: "Ponente",
    datum: "2026-07-13",
    zin: "Toelichting bij elk oordeel (waarom-regel met de doorslaggevende reden), en bij een bekende plek toont elke check meteen de uitslag zonder extra tik. Nieuwe hooikoortscheck op een eigen pollenbron (CAMS) met het rustigste blok van de dag, en drie kledingvraagpagina's (korte broek, jas, T-shirtweer). Nieuwe overzichtspagina met alle weerbeslissingen en zoekfunctie, de feedbackknoppen die niet meer wegflitsen, en op mobiel vierkante tegels plus een sticky antwoordbalk.",
  },
  {
    versie: "3.3.0",
    codenaam: "Meltemi",
    datum: "2026-07-13",
    zin: "Compacter en consistenter: elke hub-kaart volgt nu een vast stramien (vraag, verdictbadge rechts, toelichting van twee regels, eigen CTA) met het watermerk als achtergrond. Nieuwe zonkrachtcheck met huidtype en verbrandtijd. De tekstlinks verhuisden naar een uitklapmenu, de FAQ klapt in, en onder elk advies staan nu een stemmenteller, een deelknop, gerelateerde checks en een laatst-bijgewerkt-regel.",
  },
  {
    versie: "3.2.0",
    codenaam: "Sirocco",
    datum: "2026-07-13",
    zin: "De Engelse release: de hele site komt nu in twee talen uit dezelfde codebase, als Good day for it? op een eigen domein. Nieuwe check: de barbecue, avondgericht en met rook-advies dat vertelt waar je de tafel niet neerzet. Kompasstreken, decimalen en elke gegenereerde zin volgen voortaan de taal van de site.",
  },
  {
    versie: "3.1.0",
    codenaam: "Chinook",
    datum: "2026-07-13",
    zin: "Elke check antwoordt nu in zijn eigen woorden: Hang maar op, Goed te doen, Heerlijk terrasweer. De homepage opent met live antwoorden voor heel Nederland (of jouw stad), de instellingen praten mensentaal met keuzeknoppen, en de kaarten kregen kleur en karakter.",
  },
  {
    versie: "3.0.0",
    codenaam: "Levante",
    datum: "2026-07-13",
    zin: "Antwoorden in woorden: elke check zegt nu eerst Ja of Nee met een schaalwoord van Zeer slecht tot Ideaal. De homepage werd compacter en toont het live antwoord per kaart, je kunt per dag met een duim laten weten of het advies klopte, de kledingcheck kreeg een outfit-figuurtje en de teksten op de hele site werden directer.",
  },
  {
    versie: "2.2.0",
    codenaam: "Zephyr",
    datum: "2026-07-12",
    zin: "Twee nieuwe checks (kleding en terras) op een gedeelde weerbasis, het wascijfer losgetrokken van de klok (conditie-cijfer plus een aparte 'kan het nu nog?'-status met droogtijd), open-in-Maps-knoppen op de fietsroute, een rijkere hub met uitleg in gewone taal, en de hele site mobiel-eerst met meldingen en instellingen als iconen rechtsboven.",
  },
  {
    versie: "2.1.0",
    codenaam: "Mistral",
    datum: "2026-07-12",
    zin: "Auditronde: verankerde scorecurves tegen cijferinflatie, https en het echte domein overal, kaartfix, colorblind-veilige kleuren met legenda's, instellingen per check en het wegwijzer-design in leisteen en geel met Bricolage Grotesque.",
  },
  {
    versie: "2.0.0",
    codenaam: "Passaat",
    datum: "2026-07-11",
    zin: "Van losse tool naar hub: gedeelde engine met toolregister, de wascheck erbij, meldingen per route en per check, installatie op je beginscherm en programmatische pagina's per stad.",
  },
  {
    versie: "1.0.0",
    codenaam: "Kopwind",
    datum: "2026-07-11",
    zin: "De startlijn: de fietscheck met wind per stuk route, tussenstops, alternatieve routes, synccode tussen apparaten en server-push.",
  },
];
